name: energy-map
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - geopandas
  - fiona
  - shapely
  - pyproj
  - pip
  - pip:
    - pandas
    - requests
    - jupyter
    - folium
    - networkx
    - matplotlib
    - tqdm
    - python-dotenv
