base_out_path:     "/Users/dylanhartman/Library/CloudStorage/OneDrive-UniversityofWyoming/Research/Energy Modeling/energy-map/data/processed/e4st_results_v2/baseline_simplex"
gen_file:          "/Users/dylanhartman/Library/CloudStorage/OneDrive-UniversityofWyoming/Research/Energy Modeling/energy-map/data/processed/e4st_inputs/gen.csv"
bus_file:          "/Users/dylanhartman/Library/CloudStorage/OneDrive-UniversityofWyoming/Research/Energy Modeling/energy-map/data/processed/e4st_inputs/bus.csv"
branch_file:       "/Users/dylanhartman/Library/CloudStorage/OneDrive-UniversityofWyoming/Research/Energy Modeling/energy-map/data/processed/e4st_inputs/branch.csv"
hours_file:        "/Users/dylanhartman/Library/CloudStorage/OneDrive-UniversityofWyoming/Research/Energy Modeling/energy-map/data/processed/e4st_inputs/hours.csv"
nominal_load_file: "/Users/dylanhartman/Library/CloudStorage/OneDrive-UniversityofWyoming/Research/Energy Modeling/energy-map/data/processed/e4st_inputs/nominal_load.csv"
load_shape_file:   "/Users/dylanhartman/Library/CloudStorage/OneDrive-UniversityofWyoming/Research/Energy Modeling/energy-map/data/processed/e4st_inputs/load_shape.csv"
af_file:           "/Users/dylanhartman/Library/CloudStorage/OneDrive-UniversityofWyoming/Research/Energy Modeling/energy-map/data/processed/e4st_inputs/af.csv"
year_gen_data:     "y2024"
logging:           true
voll:              5000
objective_scalar:  1000
years:
  - y2025
  - y2030
  - y2035
optimizer:
  type:    "HiGHS"
  solver:  simplex
  log_to_console: true
